#ifndef MUART_CONFIG_H_
#define MUART_CONFIG_H_

	/*
	* ENABLE
	* DISABLE
	*/
#define  MUSART1_SELCTION_TO_DO       ENABLE
#define  MUSART2_SELCTION_TO_DO       ENABLE

#define  MUSART3_SELCTION_TO_DO       ENABLE

#define  MUART4_SELCTION_TO_DO        ENABLE
#define  MUART5_SELCTION_TO_DO        ENABLE

/*
 * 8 bit
 * 9 bit
 * */


	#define  MUSART1_WORD_LENGTH   8
    #define  MUSART2_WORD_LENGTH   8
    #define  MUSART3_WORD_LENGTH   8
    #define  MUART4_WORD_LENGTH    8
    #define  MUART5_WORD_LENGTH    8
	
	/*
	* ENABLE
	* DISABLE
	*/
	#define  MUSART1_TRANSMITTER  ENABLE
    #define  MUSART2_TRANSMITTER  ENABLE
    #define  MUSART3_TRANSMITTER  ENABLE
    #define  MUART4_TRANSMITTER   ENABLE
    #define  MUART5_TRANSMITTER   ENABLE

	/*
	* ENABLE
	* DISABLE
	*/

	#define  MUSART1_RECEIVER     ENABLE
	#define  MUSART2_RECEIVER     ENABLE
    #define  MUSART3_RECEIVER     ENABLE
    #define  MUART4_RECEIVER      ENABLE
    #define  MUART5_RECEIVER      ENABLE

	/*
	* ENABLE
	* DISABLE
	*/
	
	#define  MUSART1_ENABLE_INTERRUPT       ENABLE
    #define  MUSART2_ENABLE_INTERRUPT       ENABLE
    #define  MUSART3_ENABLE_INTERRUPT       ENABLE
    #define  MUART4_ENABLE_INTERRUPT        ENABLE
    #define  MUART5_ENABLE_INTERRUPT        ENABLE
	
	/*
	* 9600
	* 115200
	*/
	#define  MUSART1_BAUD_RATE      115200
    #define  MUSART2_BAUD_RATE      115200
    #define  MUSART3_BAUD_RATE      115200
    #define  MUART4_BAUD_RATE       9600
    #define  MUART5_BAUD_RATE       9600

    /*
	* ENABLE
	* DISABLE
	*/
	#define  MUSART1_TRANSMISSION_INTERRUPT  ENABLE
    #define  MUSART2_TRANSMISSION_INTERRUPT  ENABLE
    #define  MUSART3_TRANSMISSION_INTERRUPT  ENABLE
    #define  MUART4_TRANSMISSION_INTERRUPT   ENABLE
    #define  MUART5_TRANSMISSION_INTERRUPT   ENABLE

    /*
	* ENABLE
	* DISABLE
	*/
	#define  MUSART1_RECEIVER_INTERRUPT      ENABLE
    #define  MUSART2_RECEIVER_INTERRUPT      ENABLE
    #define  MUSART3_RECEIVER_INTERRUPT      ENABLE
    #define  MUART4_RECEIVER_INTERRUPT       ENABLE
    #define  MUART5_RECEIVER_INTERRUPT       ENABLE
	
#endif
